# Generated by Django 3.2.18 on 2023-04-20 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionEconomicaProductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad_principal', models.CharField(choices=[('A', 'Agricultura'), ('R', 'Artesania'), ('M', 'Mineria'), ('G', 'Gobierno'), ('T', 'Transporte'), ('C', 'Comercio'), ('E', 'Educacion'), ('U', 'Turismo'), ('I', 'Independiente'), ('O', 'Otro')], max_length=50)),
                ('actividad_secundaria', models.CharField(blank=True, choices=[('A', 'Agricultura'), ('R', 'Artesania'), ('M', 'Mineria'), ('G', 'Gobierno'), ('T', 'Transporte'), ('C', 'Comercio'), ('E', 'Educacion'), ('U', 'Turismo'), ('I', 'Independiente'), ('O', 'Otro')], max_length=50, null=True)),
                ('ingreso_total_hogar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ingreso_total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mantenimiento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dias_mes_trabajo_cultivo', models.IntegerField()),
                ('dias_mes_trabajo_no_cultivo', models.IntegerField()),
                ('es_asociado', models.BooleanField()),
                ('nombre_asociacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('etnia', models.CharField(choices=[('A', 'Afrodescendiente'), ('I', 'Indígena'), ('R', 'Raizal'), ('P', 'Palenquero'), ('G', 'Gitano'), ('N', 'Ninguna')], max_length=1)),
                ('tipo_documento', models.CharField(choices=[('C', 'Cédula'), ('E', 'Cédula extranjera'), ('P', 'Pasaporte')], max_length=1)),
                ('numero_documento', models.CharField(max_length=20)),
                ('condicion', models.CharField(choices=[('D', 'Desplazamiento'), ('V', 'Victima'), ('O', 'Otra'), ('N', 'Ninguna')], max_length=1)),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('vereda', models.CharField(max_length=50)),
                ('informacion_economica', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='productores.informacioneconomicaproductor')),
            ],
        ),
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('vereda', models.CharField(max_length=50)),
                ('tipo_predio', models.CharField(choices=[('P', 'Privada'), ('C', 'Comunal'), ('LA', 'Libre Acceso'), ('E', 'Estatal')], max_length=50)),
                ('tipo_posesion_cultivo', models.CharField(choices=[('T', 'Total'), ('F', 'Fraccionada'), ('A', 'Asociacion'), ('R', 'Arrendada')], max_length=50)),
                ('coordenadas', models.CharField(max_length=50)),
                ('altitud', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_cacao', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area_otros_cultivos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area_rastrojo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
            ],
        ),
    ]
